from logger import log

log("Test error message")
